import { Poppins } from "next/font/google";
import "./globals.css";
import localFont from 'next/font/local'

import Provider from "@/providers/Provider";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});
export const myFont = localFont({
  src: '../fonts/mayaboti-normal.ttf',
})
export const metadata = {
  title: "Hero Kidz",
  description: "Generated by Hero Kidz",
};

export default function RootLayout({ children }) {
  return (
    <Provider>
      <html lang="en">
        <body
          className={`${poppins.variable}  antialiased`}
        >
          {children}
        </body>
      </html>
    </Provider>
  );
}
