import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Shared/Navbar";
import localFont from 'next/font/local'
import Footer from "@/components/Shared/Footer";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});
export const myFont = localFont({
  src: '../fonts/mayaboti-normal.ttf',
})
export const metadata = {
  title: "Hero Kidz",
  description: "Generated by Hero Kidz",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable}  antialiased`}
      >
        <Navbar />
       <div className="max-w-7xl mx-auto">
         {children}
       </div>
       <Footer/>
      </body>
    </html>
  );
}
